version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db